conversation:
  translation_deepl_api_key: '%env(default::DEEPL_API_KEY)%'
  translation_google_api_key: '%env(default::GOOGLE_API_KEY)%'
  translation_deepl_use_free_api: true

pushword:
  apps:
    - hosts:
        - localhost.dev
        - localhost
      base_url: "https://localhost.dev"
      randomTest: 123
      generated_og_image: true
      admin_block_editor: false
      locales: "en|fr"
      page_update_notification_from: "test@example.tld"
      page_update_notification_to: "test@example.tld"
    - hosts:
        - pushword.piedweb.com
      base_url: "https://pushword.piedweb.com"
      flat_content_dir: "%kernel.project_dir%/../docs/content"
      static_dir: "%kernel.project_dir%/../../docs"
      name: Pushword
      favicon_path: "/assets/"
      static_generators:
        - Pushword\StaticGenerator\Generator\PagesGenerator
        - Pushword\StaticGenerator\Generator\MediaGenerator
        - Pushword\StaticGenerator\Generator\RobotsGenerator
        - Pushword\StaticGenerator\Generator\ErrorPageGenerator
        - Pushword\StaticGenerator\Generator\CopierGenerator
        - Pushword\StaticGenerator\Generator\CNAMEGenerator
      assets:
        javascripts:
          - "assets/app.js"
        stylesheets:
          - "assets/tw.css"
      color_bg: "#fff"
      static_copy:
        - assets
    - hosts:
        - admin-block-editor.test
      base_url: "https://admin-block-editor.test"

static_generator:
  static_symlink: false

pushword_advanced_main_image:
  main_image_formats:
    "adminPageMainImageFormatNone": 1
    "adminPageMainImageFormatNormal": 0
    "adminPageMainImageFormat13fullscreen": 2

pushword_template_editor:
  disable_creation: true
  can_be_edited_list:
    - "/pushword.piedweb.com/page/_footer.html.twig"
