twig:
    paths:
        "%pw.package_dir%/admin/src/templates": "pwAdmin"

twig_component:
    anonymous_template_directory: "components/"
    defaults:
        # Namespace & directory for components
        Pushword\Admin\Twig\Components\: "components/"
